stages: 
 - build

.job_template: &build_job_docker
  stage: build
  tags:
    - docker
  image: hdospray/docker-images:centos7
  script:
    - scripts/build_gitlab/linux.sh

.job_template: &build_job_shell
  stage: build
  tags:
    - build


### BUILD JOBS ###

build-arch-gcc:
   <<: *build_job_docker
   image: hdospray/docker-images:arch

build-centos7-gcc:
  <<: *build_job_docker

build-osx-clang:
  <<: *build_job_shell
  script:
    - scripts/build_gitlab/osx.sh
  tags:
    - osx
    - clang
