stages: 
 - build

.job_template: &build_job_docker
  stage: build
  tags:
    - docker
  image: hdospray/docker-images:centos7
  script:
    - scripts/build_gitlab/linux.sh

.job_template: &build_job_shell
  stage: build
  tags:
    - build


### BUILD JOBS ###

build-arch-gcc:
   <<: *build_job_docker
   image: hdospray/docker-images:arch

build-centos7-gcc:
  <<: *build_job_docker

#build-osx-clang:
#  <<: *build_job_shell
#  script:
#    - scripts/build_gitlab/osx.sh
#  tags:
#    - osx
#    - clang

#build-windows-msvc15:
#  <<: *build_job_shell
#  script:
#    - scripts\build_gitlab\win.bat "Visual Studio 15 2017 Win64" "v141" "OFF"
#  tags:
#    - msvc15
#    - win7
#  artifacts:
#    paths:
#      - build/Release
#      - build/regression_tests
#    expire_in: 3 day
