stages: 
 - build

.job_template: &build_job_docker
  stage: build
  tags:
    - docker
  image: hdospray/docker-images:centos7
  script:
    - scripts/build_gitlab/linux.sh


### BUILD JOBS ###

      #build-arch-gcc:
      #  <<: *build_job_docker

build-centos7-gcc:
  <<: *build_job_docker
