## Copyright 2020-2021 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

stages:
 - build
 - pre-scan
 - scan

.job_template: &centos7
  tags: [ docker, modules ]
  image: $DOCKER_REGISTRY/centos:7

.job_template: &build_job_docker
  stage: build
  tags:
    - docker
  image: hdospray/docker-images:centos7
  script:
    - scripts/build_gitlab/linux.sh

.job_template: &build_job_docker_modules
  stage: build
  tags:
    - docker
    - modules
  image: hdospray/docker-images:centos7-mod
  script:
    - scripts/build_gitlab/linux.sh

.job_template: &build_job_shell
  stage: build
  tags:
    - build


### BUILD JOBS ###


build-ubuntu20.04-gcc:
      <<: *build_job_docker
      image: hdospray/docker-images:ubuntu20.04
      script:
           - scripts/build_gitlab/linux.sh

             #build-centos7-gcc:
             #      <<: *build_job_docker
             #      image: hdospray/docker-images:centos7
             #      script:
             #           - scl enable devtoolset-8 -- bash
             #           - scripts/build_gitlab/linux.sh

             #build-centos7-icc:
             #   <<: *build_job_docker_modules
             #   script:
             #     - module load cmake
             #     - module load intel
             #     - export CC=icc
             #     - export CXX=icpc
             #     - export CXXFLAGS="-std=c++17"
             #     - scripts/build_gitlab/linux.sh

build-kw-scan:
  stage: pre-scan
  tags: [docker]
  image: hdospray/docker-images:centos7
  script:
    - scripts/build_gitlab/linux-kw.sh
  artifacts:
    paths:
      - ./klocwork/*
  needs: []

check-kw-issues:
  stage: scan
  image: $DOCKER_REGISTRY/ospray/docker-images:centos7
  needs: [build-kw-scan]
  tags: [docker]
  script:
    - scripts/scan_gitlab/kw-check-issues.sh

gen-kw-report:
  stage: scan
  image: $DOCKER_REGISTRY/ospray/docker-images:centos7
  needs: [build-kw-scan]
  tags: [docker]
  script:
    - scripts/scan_gitlab/kw-gen-report.sh
    - scripts/scan_gitlab/store-files.sh $CI_PROJECT_NAME $CI_PIPELINE_ID klocwork "klocwork/report.log"
  artifacts:
    paths:
      - ./klocwork/*

protex:
  <<: *centos7
  stage: scan
  needs: []
  script:
    - $CI_TOOLS_PATH/bin/protex.sh
