stages: 
 - build

.job_template: &build_job_docker
  stage: build
  tags:
    - docker
  image: ospray/docker-images:arch
  script:
    - scripts/build_gitlab/linux.sh


### BUILD JOBS ###

build-arch-gcc:
  <<: *build_job_docker