## Copyright 2023 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

  workflow_dispatch:

permissions: read-all

jobs:

    build-ubuntu20-04:
      secrets: inherit
      uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@devel
      with:
        image: hdospray/ubuntu:20.04-cb-hdospray23.02
        cmd: |
          scripts/build_ci/linux.sh
